--CONSULTA A
SELECT
    V.VDA_CODIGO   AS CODIGO_VENDA,
    V.VDA_DATA     AS DATA,
    CP.PES_NOME    AS NOME_CLIENTE,
    V.VDA_TOTAL    AS TOTAL_VENDA
FROM
    VENDA V
    INNER JOIN (
        SELECT
            P.PES_NOME,
            C.CLI_CODIGO,
            P.PES_UF
        FROM
            CLIENTE   C
            INNER JOIN PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
    ) CP ON V.CLI_CODIGO = CP.CLI_CODIGO
WHERE
    ( V.VDA_DATA BETWEEN '01.01.2000' AND CURRENT_DATE )
    AND CP.PES_UF LIKE 'SP';

--CONSULTA A - MELHORADA
SELECT
    V.VDA_CODIGO   AS CODIGO_VENDA,
    V.VDA_DATA     AS DATA,
    P.PES_NOME     AS NOME_CLIENTE,
    V.VDA_TOTAL    AS TOTAL_VENDA
FROM
    VENDA V
    INNER JOIN 
            CLIENTE   C  ON V.CLI_CODIGO = C.CLI_CODIGO
    INNER JOIN 
            PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
WHERE
    ( V.VDA_DATA BETWEEN '01.01.2000' AND CURRENT_DATE )
    AND P.PES_UF LIKE 'SP';




--CONSULTA B
SELECT
    C.CPR_CODIGO    AS CODIGO_COMPRA,
    C.CPR_EMISSAO   AS DATA_EMISSÃO,
    U.USU_NOME      AS NOME_USUARIO,
    FP.PES_NOME     AS NOME_FORNECEDOR
FROM
    COMPRA    C
    INNER JOIN USUARIO   U ON U.USU_CODIGO = C.USU_CODIGO
    INNER JOIN (
        SELECT
            F.FOR_CODIGO,
            P.PES_NOME,
            P.PES_FISICA
        FROM
            FORNECEDOR   F
            INNER JOIN PESSOA       P ON F.PES_CODIGO = P.PES_CODIGO
    ) FP ON FP.FOR_CODIGO = C.FOR_CODIGO
WHERE
    ( U.USU_NOME LIKE '%E%' )
    AND ( U.USU_ATIVO LIKE 'S' )
    AND ( FP.PES_FISICA = 'N' );


--CONSULTA B - MELHORADA
SELECT
    C.CPR_CODIGO    AS CODIGO_COMPRA,
    C.CPR_EMISSAO   AS DATA_EMISSÃO,
    U.USU_NOME      AS NOME_USUARIO,
    P.PES_NOME      AS NOME_FORNECEDOR
FROM
    COMPRA    C
    INNER JOIN USUARIO   U ON U.USU_CODIGO = C.USU_CODIGO
    INNER JOIN 
            FORNECEDOR   F ON F.FOR_CODIGO = C.FOR_CODIGO
            INNER JOIN PESSOA       P ON F.PES_CODIGO = P.PES_CODIGO
    WHERE
    ( U.USU_NOME LIKE '%E%' )
    AND ( U.USU_ATIVO LIKE 'S' )
    AND ( P.PES_FISICA = 'N' );


--CONSULTA C
SELECT
    VP.*
FROM
    VENDA_PAGTO VP
    INNER JOIN (
        SELECT
            CP.PES_NOME,
            CP.PES_FISICA,
            V.VDA_CODIGO,
            V.VDA_TOTAL,
            V.VDA_DATA
        FROM
            VENDA V
            INNER JOIN (
                SELECT
                    C.CLI_CODIGO,
                    P.PES_FISICA,
                    P.PES_NOME
                FROM
                    CLIENTE   C
                    INNER JOIN PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
            ) CP ON V.CLI_CODIGO = CP.CLI_CODIGO
    ) VCP ON VP.VDA_CODIGO = VCP.VDA_CODIGO
WHERE
    ( VP.FPG_CODIGO = 1 )
    AND ( VCP.PES_FISICA LIKE 'S' )
    AND ( VCP.VDA_TOTAL BETWEEN 100 AND 2560 )
    AND ( VCP.VDA_DATA BETWEEN '01.01.2010' AND '21.12.2018' )
ORDER BY
    VCP.PES_NOME;


--CONSULTA C - MELHORADA
SELECT
    VP.*
FROM
    VENDA_PAGTO VP
    INNER JOIN 
            VENDA V ON VP.VDA_CODIGO = V.VDA_CODIGO
            INNER JOIN
                    CLIENTE   C ON V.CLI_CODIGO = C.CLI_CODIGO
                    INNER JOIN PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
WHERE
    ( VP.FPG_CODIGO = 1 )
    AND ( P.PES_FISICA LIKE 'S' )
    AND ( V.VDA_TOTAL BETWEEN 100 AND 2560 )
    AND ( V.VDA_DATA BETWEEN '01.01.2010' AND '21.12.2018' )
ORDER BY
    P.PES_NOME;


--CONSULTA D
SELECT
    CP.PES_NOME AS NOME_PESSOA,
    COUNT(*) AS QUANTIDADE,
    SUM(VDA_TOTAL) AS SOMA
FROM
    VENDA V
    INNER JOIN (
        SELECT
            C.CLI_CODIGO,
            P.PES_NOME
        FROM
            CLIENTE   C
            INNER JOIN PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
    ) CP ON CP.CLI_CODIGO = V.CLI_CODIGO GROUP BY (CP.PES_NOME) ORDER BY CP.PES_NOME;


--CONSULTA D - MELHORADA
SELECT
    P.PES_NOME AS NOME_PESSOA,
    COUNT(*) AS QUANTIDADE,
    SUM(VDA_TOTAL) AS SOMA
FROM
    VENDA V
    INNER JOIN 
            CLIENTE   C ON C.CLI_CODIGO = V.CLI_CODIGO
            INNER JOIN PESSOA    P ON C.PES_CODIGO = P.PES_CODIGO
 GROUP BY (P.PES_NOME) ORDER BY P.PES_NOME;



--CONSULTA E
SELECT
    P.PRO_CODIGO      AS CODIGO_PRODUTO,
    P.PRO_NOME        AS NOME,
    CP.CPR_QTDE       AS QUANTIDADE,
    CP.CPR_PRECO      AS PREÇO,
    CP.CPR_DESCONTO   AS DESCONTO,
    CP.CPR_TOTAL      AS TOTAL
FROM
    COMPRA_PRODUTO   CP
    INNER JOIN PRODUTO          P ON P.PRO_CODIGO = CP.CPR_CODIGO
    INNER JOIN COMPRA           C ON C.CPR_CODIGO = CP.CPR_CODIGO
WHERE
    ( P.PRO_ATIVO LIKE 'N' )
    AND ( P.PRO_CODIGO BETWEEN 2 AND 100 )
        AND ( P.PRO_NOME LIKE '%A%' )
            AND ( C.CPR_EMISSAO IS NULL );
